"""Add clerk_id to users

Revision ID: 8f9c049a0bbb
Revises: e3f4cec3945d
Create Date: 2026-06-07 18:41:36.034302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9c049a0bbb'
down_revision: Union[str, Sequence[str], None] = 'e3f4cec3945d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_id', sa.Text(), nullable=True), schema='app_schema')
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='app_schema')
    op.create_unique_constraint(None, 'users', ['clerk_id'], schema='app_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='app_schema', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='app_schema')
    op.drop_column('users', 'clerk_id', schema='app_schema')
    # ### end Alembic commands ###
