"""updated models after initial implementations

Revision ID: bac9d5d63daa
Revises: 93b3d233b8cd
Create Date: 2026-03-18 19:04:27.697128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac9d5d63daa'
down_revision: Union[str, Sequence[str], None] = '93b3d233b8cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('body_part', sa.Text(), nullable=True),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('gif_url', sa.Text(), nullable=True),
    sa.Column('target', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='app_schema'
    )
    op.create_table('body_weight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('logged_at', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('exercise_instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('instruction', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['app_schema.exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('exercise_secondary_muscles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('muscle', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['app_schema.exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('mesocycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('weeks', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("goal IN ('strength', 'hypertrophy', 'endurance', 'weight_loss', 'maintenance')", name='mesocycles_goal_check'),
    sa.ForeignKeyConstraint(['user_id'], ['app_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('achieved_on', sa.Date(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['app_schema.exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fitness_level', sa.String(), nullable=True),
    sa.Column('preferred_unit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('workout_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('mesocycle_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('perceived_exertion', sa.Integer(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mesocycle_id'], ['app_schema.mesocycles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['app_schema.workout_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('workout_template_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('target_rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['app_schema.exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['app_schema.workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    op.create_table('exercise_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.String(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('is_pr', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['app_schema.exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['app_schema.workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_sets', schema='app_schema')
    op.drop_table('workout_template_exercises', schema='app_schema')
    op.drop_table('workout_sessions', schema='app_schema')
    op.drop_table('workout_templates', schema='app_schema')
    op.drop_table('user_profiles', schema='app_schema')
    op.drop_table('personal_records', schema='app_schema')
    op.drop_table('mesocycles', schema='app_schema')
    op.drop_table('exercise_secondary_muscles', schema='app_schema')
    op.drop_table('exercise_instructions', schema='app_schema')
    op.drop_table('body_weight_logs', schema='app_schema')
    op.drop_table('users', schema='app_schema')
    op.drop_table('exercises', schema='app_schema')
    # ### end Alembic commands ###
